"""Fix password_hash length and add show_on_leaderboard

Revision ID: 02d721fa00d0
Revises: 3ebb5d79182a
Create Date: 2025-05-25 11:29:20.663098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02d721fa00d0'
down_revision = '3ebb5d79182a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wrong_guesses',
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('guessed_name', sa.String(), nullable=False),
    sa.Column('guessed_bias', sa.Integer(), nullable=False),
    sa.Column('guessed_establishment', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('outlet_id', 'guessed_name', 'guessed_bias', 'guessed_establishment')
    )
    op.drop_table('user_outlet_progress')
    op.drop_table('submissions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='submissions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='submissions_pkey'),
    sa.UniqueConstraint('url', name='submissions_url_key')
    )
    op.create_table('user_outlet_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('outlet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guessed_name_correct', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('guessed_bias_correct', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('guessed_establishment_correct', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('all_correct_on_first_try', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], name='user_outlet_progress_outlet_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_outlet_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_outlet_progress_pkey'),
    sa.UniqueConstraint('user_id', 'outlet_id', name='user_outlet_progress_user_id_outlet_id_key')
    )
    op.drop_table('wrong_guesses')
    # ### end Alembic commands ###
