"""Add outlet_id to submissions

Revision ID: 66c5d0bbc95a
Revises: d22e8ba1e61a
Create Date: 2025-05-25 19:17:47.125818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c5d0bbc95a'
down_revision = 'd22e8ba1e61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outlet_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('outlet_id')

    # ### end Alembic commands ###
