"""Make outlet_id not nullable

Revision ID: 811c1bb01b74
Revises: 66c5d0bbc95a
Create Date: 2025-05-25 19:44:23.770419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811c1bb01b74'
down_revision = '66c5d0bbc95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('outlet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('outlet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
