"""Add user_outlet_progress table

Revision ID: e85015709e08
Revises: 02d721fa00d0
Create Date: 2025-05-25 11:34:42.612577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85015709e08'
down_revision = '02d721fa00d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_outlet_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('guessed_name_correct', sa.Boolean(), nullable=True),
    sa.Column('guessed_bias_correct', sa.Boolean(), nullable=True),
    sa.Column('guessed_establishment_correct', sa.Boolean(), nullable=True),
    sa.Column('all_correct_on_first_try', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'outlet_id', name='user_outlet_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_outlet_progress')
    # ### end Alembic commands ###
